spring.application.name=backend

spring.profiles.active=${PROFILE:dev}

spring.datasource.url=jdbc:postgresql://${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DDL:create-drop}

jwt.secret=${JWT_SECRET}
